Section A: Data Structures & Control Structures

1.	Create a list of 5 integers. Perform and print the result of the following operations: append, extend, insert, remove, pop, clear, index, count, sort, and reverse.

In [ ]:
list = [10, 20, 30, 40, 50]
print(f"List: {list}")

#append - adding element to end (60)
list.append(60)
print(f"List after append: {list}")

#extend - add multiple elements to the end
list.extend([70, 80])
print(f"List after extend: {list}")

#insert - inserting element at a specific positon
list.insert(2, 25)
print(f"List after insert: {list}")

#remove - removing a aspecifc element
list.remove(20)
print(f"List after remove: {list}")

#pop - remove and return element at index
popped = list.pop(3)
print(f"After pop(3): {list}")

#clear - remove all elements
list1 = list.copy()
list1.clear()
print(f"After clear: {list1}")

#index - find index of first occurence
index_of_50 = list.index(50)
print(f"Index of 50 : {index_of_50}")

#count - count occureneces of a value
list.append(10)
count_of_10 = list.count(10)
print(f"Count of 10: {count_of_10}")

#sort - sort list in ascending order
list.sort()
print(f"After sort: {list}")

#reverse - reverse the list order
list.reverse()
print(f"After reverse: {list}")


List: [10, 20, 30, 40, 50]
List after append: [10, 20, 30, 40, 50, 60]
List after extend: [10, 20, 30, 40, 50, 60, 70, 80]
List after insert: [10, 20, 25, 30, 40, 50, 60, 70, 80]
List after remove: [10, 25, 30, 40, 50, 60, 70, 80]
After pop(3): [10, 25, 30, 50, 60, 70, 80]
After clear: []
Index of 50 : 3
Count of 10: 2
After sort: [10, 10, 25, 30, 50, 60, 70, 80]
After reverse: [80, 70, 60, 50, 30, 25, 10, 10]


2.	Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why.

In [ ]:
"""
Tuples cant be modified, once a tuple has been created data stays same, tuples
are immutable objects anda re fater to access and hence tuples can be used as
dictonary keys
"""
student = ("Aditya", "Amit", "Sunag")
print(f"Tuple: {student}")

#attempt to change the tuple
print("\nTrying to change 'Aditya' to 'Siddharth'")
try:
  student[1] = "Siddharth"
except TypeError as e:
  print(f"Error occurred: {e}")
  print(f"Tuples are immutable!")

Tuple: ('Aditya', 'Amit', 'Sunag')

Trying to change 'Aditya' to 'Siddharth'
Error occurred: 'tuple' object does not support item assignment
Tuples are immutable!


3.	Create a set of integers with some duplicate values. Print the set and explain the output.

In [ ]:
set = {1, 2, 2, 3, 4, 4, 4, 5}
print(f"Set: {set}")
print(f"Type: {type(set)}")

#Explanation
print(f"Sets automatically removes the duplicate values \nOriginal values: 1, 2, 2, 3, 4, 4, 4, 5")

Set: {1, 2, 3, 4, 5}
Type: <class 'set'>
Sets automatically removes the duplicate values 
Original values: 1, 2, 2, 3, 4, 4, 4, 5


4.	Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary.

In [ ]:
details = {'name': 'Nick', 'age': 25, 'city': 'Canada'}
print(f"Record: {details}")

#updating age and adding email
details['age'] = 26
details['email'] = 'nick@gmail.com'
print(f"Updated record: {details}")

Record: {'name': 'Nick', 'age': 25, 'city': 'Canada'}
Updated record: {'name': 'Nick', 'age': 26, 'city': 'Canada', 'email': 'nick@gmail.com'}


  5.  Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message.

In [ ]:
age = int(input("Enter your age: "))

if age < 0:
  print(f"Invalid age!")
elif age < 18:
  print(f"You are not eligible to vote!")
elif age >= 18:
  print(f"You are eligible to vote")

Enter your age: 17
You are not eligible to vote!


6.	Given a 'marks' variable, print the grade:
- 90 and above: 'A'
- 75–89: 'B'
- 50–74: 'C'
- Below 50: 'Fail'


In [ ]:
marks = int(input("Enter your marks: "))

if marks >= 90:
  print("A")
elif marks >= 75:
  print("B")
elif marks >=50:
  print("C")
else:
  print("Fail")

Enter your marks: 90
A


7.	Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative

In [ ]:
num = int(input("Enter a number: "))

if num > 0:
  if num % 2 == 0:
        print("Positive and Even")
  else:
        print("Positive but Odd")
elif num < 0:
    print("Negative")
else:
    print("Zero")

Enter a number: 5
Positive but Odd


Section - B : Numpy

8.	Create:
- A scalar using np.array(5)
- A 1D array with values 1 to 5
- A 2D array (2x3) with values from 10 to 60 in steps of 10


In [ ]:
import numpy as np

#creating a scalar
scalar = np.array(5)
print(f"Scalar: {scalar}\n")

#creating a 1D array
array1 = np.array([1, 2, 3, 4, 5])
print(f"1D Array: {array1}\n")

#creating a 2D array
array2 = np.array([[10, 20, 30], [40, 50, 60]])
print(f"2D Array: \n {array2}")

Scalar: 5

1D Array: [1 2 3 4 5]

2D Array: 
 [[10 20 30]
 [40 50 60]]


9.	Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().

In [2]:
import numpy as np

#it generates 4x4 array of random integers between 0 and 100
random_matrix =np.random.randint(0, 100, size =(4, 4))

print(f"Random Matrix: \n{random_matrix}")

Random Matrix: 
[[ 4  4 29 70]
 [ 2 69 94 97]
 [22 16 25 42]
 [ 1 10 82 35]]


10.	Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.

In [3]:
import numpy as np
import pandas as pd

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print(f"Original Matrix: \n{matrix}")

df = pd.DataFrame(matrix, columns = ['A', 'B', 'C'])

print(f"\nDataFrame: \n{df}")

Original Matrix: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]

DataFrame: 
   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9


Section C: Exploring Pandas

11.	Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then:
- Use .info(), .describe()
- Select 'Name' and 'City' columns
- Drop 'City' column
- Fill any missing values in 'Salary' column with the mean
- Remove any duplicate rows


In [17]:
import pandas as pd
import numpy as np


df = pd.DataFrame({
    'Name': ['Rahul','Aman','Ankit','Siddharth','Aditya','Divyanshu','Hemant','Ravi','Neha','Anjali'],
    'Age': [28, 25, 23, 24 ,27, 29, 30, 35, 23, 22],
    'City': ['Delhi', 'Mumbai', 'Bangalore', 'Chennai', 'Delhi', 'Chennai', 'Mumbai', 'Bangalore', 'Delhi', 'Bangalore'],
    'Salary': [45000, 52000, 68000, np.nan, 51000, 48000, 75000, 54000, 59000, 47000]
})

print(df)
print()

#info to show structures
print(df.info())
print()

#describe shows summary statistics
print(df.describe())
print()

#select specific columns
print(df[['Name', 'City']])
print()

#drop a column
df.drop('City', axis = 1, inplace = True)
print(df)
print()

#filling missing data with mean
mean_salary = df['Salary'].mean()
df['Salary'].fillna(mean_salary, inplace = True)
print(df)
print()

#remove duplicates if any
df.drop_duplicates(inplace = True)
print(df)

        Name  Age       City   Salary
0      Rahul   28      Delhi  45000.0
1       Aman   25     Mumbai  52000.0
2      Ankit   23  Bangalore  68000.0
3  Siddharth   24    Chennai      NaN
4     Aditya   27      Delhi  51000.0
5  Divyanshu   29    Chennai  48000.0
6     Hemant   30     Mumbai  75000.0
7       Ravi   35  Bangalore  54000.0
8       Neha   23      Delhi  59000.0
9     Anjali   22  Bangalore  47000.0

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     10 non-null     int64  
 2   City    10 non-null     object 
 3   Salary  9 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes
None

             Age        Salary
count  10.000000      9.000000
mean   26.600000  55444.444444
std     4.033196  10137.937550
min    22.000000  45000.000000
25%    23.250000  48000.000000

/tmp/ipython-input-1221892349.py:34: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Salary'].fillna(mean_salary, inplace = True)
